# Generated by Django 4.1.2 on 2022-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('overall', models.CharField(choices=[('horrible', 'Horrible'), ('average', 'Average'), ('good', 'Good'), ('great', 'Great'), ('fantastic', 'Fantastic')], max_length=120)),
                ('pace', models.CharField(choices=[('too_fast', 'Too Fast'), ('too_slow', 'Too Slow'), ('just_right', 'Just Right')], max_length=120)),
                ('language', models.CharField(choices=[('csharp', 'C#'), ('cplusplus', 'C++'), ('javascript', 'JavaScript'), ('php', 'PHP'), ('swift', 'Swift'), ('java', 'Java'), ('go', 'Go'), ('sql', 'SQL'), ('ruby', 'Ruby')], max_length=120)),
            ],
        ),
    ]
